import sys
import datetime
import time
from pushbullet import Pushbullet
import random

api_key = open('/home/pi/APIConfigs/Pushbulletkey.config', 'r').read() #read Pushbullet Key from /home/pi/Pushbulletkey.config file
api_key = api_key.replace("\n", "") #Remove Whitespace
#print api_key
pb = Pushbullet(api_key) 

jokes = ['Q: What do ghosts eat for supper? A: Spooketi', 
'Q: What do you do when 50 zombies surround your house? A: Hope its Halloween!!', 
'Q: What is the most important subject a witch learns in school? A: Spelling.', 
'Q: Why didnt the skeleton want to go to school? A: His heart wasnt in it.', 
'Q: Why didnt the skeleton cross the road? A: He didnt have any guts!', 
'Q: Why did the skeleton cross the road? A: To get to the body shop.', 
'Q: Why didnt the skeleton go to the ball? A: Because he had no BODY to go with.', 
'Q: What did the little girl say when she had to choose between a tricycle and a candy bar? A: Trike or Treat?', 
'Q: What do you call a fat pumpkin? A: A plumpkin.', 
'Q: What room does a ghost not need? A: A living room!', 
'Q: Why are ghosts so bad at lying? A: Because you can see right through them!', 
'Q: Who did Frankenstein take to the dance? A: His ghoul friend!', 
'Q: Why is Supermans costume so tight? A: Because he wears a size S.', 
'Q: What do ghosts use to wash their hair? A: Shamboo!', 
'Frankenstein: Witch can you make me a lemonade? Witch: Poof you are a lemonade!', 
'Q: What do you get when you cross a witch with sand? A: A sandwich!', 
'Q: What is a vampires favorite fruit? A: A nectarine!', 
'Mommy, everyone says I look like a werewolf. Please be quiet and comb your face.', 
'Q: What kind of dessert does a ghost like? A: I scream!', 
'Q: When is it bad luck to be followed by a black cat? A: When youre a mouse.', 
'Q: What do birds say on Halloween? A: Twick o tweet', 
'Q: What do you get when you cross a Cocker Spaniel, a Poodle and a ghost? A: A cocker poodle boo.', 
'Q: What do moms dress up as on Halloween? A: Mummies!', 'Q: What is a ghosts favorite fruit? A: Booberries!', 
'Q: What does a skeleton say before dinner? A: Bone appetit!', 
'Q: What does a witch use to keep her hair up? A: Scarespray!', 
'Q: What do you get when you cross a snowman with a vampire? A: Frostbite.', 
'Q: What kind of pants do ghosts wear? A: Boo-Jeans.', 
'Q: Why do ghosts make good cheerleaders? A: Because they have a lot of spirit.', 
'Q: What did one owl say to the other owl? A: Happy Owl-ween!', 
'Q: Why is a skeleton so mean? A: He doesnt have a heart.', 
'Q: What goes around a haunted house and never stops? A: A fence.', 
'Q: What did the ghost say to the other ghost? A: Do you believe in humans?', 
'Q: What do vampires take when they are sick? A: Coffin drops!', 
'Q: What do you get when you cross a duck with a vampire? A: Count Quackula!', 
'Q: What is a ghosts favorite pie? A: Booberry pie!', 
'Q: Where do ghosts buy their food? A: At the ghost-ery store!', 
'Q. What do goblins and ghosts drink when theyre hot and thirsty on Halloween? A. Ghoul-aid!!!', 
'Q. What is a Mummies favorite type of music? A. Wrap!!!!!', 
'Q. Why do demons and ghouls hang out together? A. Because demons are a ghouls best friend!', 
'Q. Whats a monsters favorite bean? A. A human bean.', 
'Q. Why cant the boy ghost have babies? A. Because he has a Hallo-weenie.', 
'Q. What do you call a witch who lives at the beach? A. A sand-witch.', 
'Q. Where does a ghost go on Saturday night? A. Anywhere where he can boo-gie.', 
'Q. What did the skeleton say to the vampire? A. You suck.', 
'Q. What do ghosts say when something is really neat? A.Ghoul', 
'Q. Why did the ghost go into the bar? A. For the Boos.', 
'Q. Why was the girl afraid of the vampire? A. He was all bite and no bark.', 
'Q. Why did the game warden arrest the ghost? A. He didnt have a haunting license.', 
'Q. Why didnt the skeleton dance at the party? A. He had no body to dance with.', 
'Q. Where does Count Dracula usually eat his lunch? A. At the casketeria.', 
'Q. What happens when a ghost gets lost in the fog? A. He is mist.', 
'Q. Where did the goblin throw the football? A. Over the ghoul line.', 
'Q. Why doesnt Dracula mind the doctor looking at his throat. A. Because of the coffin.', 
'Q. Why is a ghost such a messy eater? A. Because he is always a goblin.', 
'Q. What do you call a goblin who gets too close to a bonfire? A. A toasty ghosty.', 
'Q. Why did the Vampire read the Wall Street Journal? Q. He heard it had great circulation.', 
'Q. What tops off a ghosts ice cream sundae? A. Whipped scream.', 
'Q. What do you give a skeleton for valentines day? A. Bone-bones in a heart shaped box.', 
'Q. What are ghosts favorite kind of streets? A. Dead ends', 
'Q. What is a vampires favorite holiday? A. Fangsgiving', 
'Q. What kind of makeup do ghosts wear? A. Mas-scare-a.', 
'Q. Why did the skeleton cross the road? A. To go to the body shop.', 
'Q. What happens when two vampires meet? A. It was love at first bite!', 
'Q. Who was the most famous ghost detective? A. Sherlock Moans.', 
'Q. What do you call two spiders that just got married? A. Newlywebbed', 
'Q. What is a ghosts favorite place on the web? A. www.halloween.com!', 
'Q. Who was the most famous witch detective? A. Warlock Holmes', 
'Q. What did the ghost say to the man at the coffee shop? A. Scream or sugar!', 
'Q. Who was the most famous skeleton detective? A. Sherlock Bones.', 
'Q. Who was the most famous French skeleton? A. Napoleon bone-apart', 
'Q. Which building does Dracula visit in New York? A. The Vampire State Building.', 
'Q. Where do most werewolves live? A. In howllywood, California', 
'Q. Where do most goblins live? A. in North and South Scarolina.', 
'Q. Where does a ghost refuel his porche? A. At a ghastly station.', 
'Q. What do Italians eat on Halloween? A. Fettucinni Afraid-o (Ha ha ha)', 
'Q. Why did the skeleton go disco dancing? A. to see the boogy man.', 
'Q. What do witches use in their hair? A. scare-spray', 
'Q. What do you call a little monsters parents A. mummy and deady', 
'Q. What do you get when you cross a black cat with a lemon. A. sour-puss', 
'Q. How do you scare a mummy A. with a yummy dummy in a crash test crummy.', 
'Q. What do you get when you cross a vampire with the internet? A. blood-thirsty hacker baby', 
'Q. What do you get when you cross a pumpkin with a skwaush? A. a squashed pumpkin pie.', 
'Q. Why do ghosts shiver and moan? A. Its drafty under that sheet.', 
'Q. What instrument do skeleton play? A: Trom-BONE.', 
'Q. What do ghosts eat for breakfast? A. Boo-Berries.', 
'Q. What is a vampires favorite place on the web? A. www.halloween.com!', 
'Q: Why didt the skeleton cross the road? A: He had no guts.', 
'Q. Why do vampires scare people? A. They are bored to death!', 
'Q. How can you tell a vampire likes baseball? A. Every night he turns into a bat.', 
'Q. Whats it like to be kissed by a vampire? A. Its a pain in the neck.', 
'Q. How can you tell when a vampire has been in a bakery? A. All the jelly has been sucked out of the jelly doughnuts.', 
'Q. What songs does Dracula hate? A. You Are My Sunshine and Sunshine on my Shoulders.', 
'Q. What did the Mummy movie director say when the final scene was done? A. Ok, thats a wrap.', 
'Q. How does a girl vampire flirt? A. She bats her eyes.', 
'Q. What is a vampires least favorite food? A.Steak', 
'Q. Whats it called when a vampire has trouble with his house? A. A grave problem.', 
'Q. Why doesnt anybody like Dracula? A. He has a bat temper.', 
'Q. Why did Dracula go to the dentist? A. He had a fang-ache.', 
'Q. Why are vampires like false teeth? A. They all come out at night.', 
'Q. Who does Dracula get letters from? A. His fang club.', 
'Q. What kind of key does a skeleton use? A. A skeleton key.', 
'Q. What kind of gum do ghosts chew? A. Boo Boo Gum.', 
'Q. Why did Dracula take cold medicine? A. To stop his coffin.', 
'Q. Why does Dracula wear patent leather shoes? A. Sandals dont look good with his tuxedo.', 
'Q. How do you keep a monster from biting his nails? A. Give him screws.', 
'Q. What cant you give the headless horseman? A. A headache.', 
'Q. Why did the headless horseman go into business? A. He wanted to get ahead in life.', 
'Q. What is a ghosts favorite sale? A. A white sale.', 
'Q. What kind of tie does a ghost wear to a formal party? A. A boo-tie.', 
'Q. Whats a ghosts favorite desert? A. Boo-berry pie.', 
'Q. What type of dog does every vampire have? A. Bloodhound!', 
'Q. Whats a monsters favorite desert? A. I-Scream!!', 
'Q. Why o girl ghosts go on diets? A. So they can keep their ghoulish figures.', 
'Q. When does a ghost have breakfast? A. In the moaning.', 
'Q. What do ghosts drink at breakfast? A. Coffee with scream and sugar.', 
'Q. Where does a ghost go on vacation? A. Mali-boo.', 
'Q. Where does a ghost go on Saturday night? A. Anywhere where he can boo-gie.', 
'Q. Where did the ghost get its hair done? A: At the boo-ty shop.', 
'Q. Riddle: the maker does not want, it the buyer does not use it, and the user does not see it, what is it? A. a coffin.', 
'Q. What do they teach in witching school? A. Spelling.', 
'Q. Why does a witch ride a broom? A. Vacuum cleaners get stuck at the end of the cord.', 
'Q. What do you call a witchs garage? A. A broom closet.', 
'Q. What do you call two witches living together? A. Broommates.', 
'Q. Why dont mummies take vacations? A. Theyre afraid theyll relax and unwind.', 
'Q. What is a witchs favorite subject in school? A. Spelling', 
'Q: Why cant Boy Ghosts make babies?? A: Because they have Hollow-Weenies!', 
'Q. Why did the man with a knife in his head cross the street? A. He was dying to get to the other side!!', 
'Q. Where do ghosts go out? A. Where they can get boooooo-ze.', 
'Q. Where do ghosts go out? A. Where they can get sheet-faced.', 
'Q. What did the mother ghost say to her kids in the car? A. Fasten your sheet belts.', 
'Q. Why didnt the skeleton go to see a scary movie? A. He didnt have the guts.', 
'Q. What did the corpse mom do when her son was bad? A. Ground him', 
'Q. Why was the mummy so tense? A. Because he was all wound up.', 
'Q. Why did the vampire need mouthwash? A. Because he had bat breath.', 
'Q. Why dont ghost have bands? A. They get booooooooooed.', 
'Q. What do you call a monster who poisons corn flakes? A. A cereal killer.', 
'Q. Who are some of the werewolves cousins? A. The whatwolves, the whowolves and the when wolves.', 
'Q. What did the bird say on Halloween? A. Trick or tweet!', 
'Q. Why do skeletons drink milk? A. To help their bones!', 
'Q. Whats a Vampires least favourate song? A. Another one bites the dust!', 
'Q. What is a Skeletons favorite song. A. Bad to the Bone', 
'Q. Whats a ghosts favorate type of car? A. A boo-ick', 
'Q. Where do ghost go for fun? A. To the boo-vies', 
'Q. Whats a skeletons favorite part of the house? A. the living room', 
'Q. What did the teenage witch ask her mother on Haloween? A. Can i have the keys to the broom tonight.', 
'Q. What do u get when theres a witch in the desert? A. You get a sandwich.', 
'W. Why do ghosts like to ride elevators? A.it raises their spirits.', 
'Q. Why cant a Skeleton Lift Weights? A. Hes all bone & no muscle.', 
'Q. What is a vamires favorite fruit? A: A necktarine', 
'Q. What do the skeletons say be for eating? A. Bone appetite', 
'Q. What do gosts call there girl friends? A. There goul friends.', 
'Q. How did the ghost say goodbye to the vampire? A. So long sucker!', 
'Q. What did the goblin say to the witch? A. I dont know you tell me!', 
'Q. Why dident the skeleten go to the halloween party? A. Becuse he had no body to go with.', 
'Q. What is a ghosts favorite band? A. The Boos Brothers', 'Q. What did Dracula have for dessert? A. Whine & Ice scream', 
'Q. What is Draculas favorite restaraunt? A. Murder King', 
'Q. What is a Ghosts favorite food? A. HamBoogers', 
'Q. What is in a ghosts nose? A. Boogers', 
'Q. What was the mummies vacation like? A. Nobody knows. They were too wrapped up to tell us.', 
'Q: What did tha boy ghost say to the girl ghost? A: You are the most booooooooo-tiful thing I have ever seen!', 
'Q. Why does a cemetery have to keep a fence around it? A. Because people are dying to get in.', 
'Q. What do you give to a pumpkin who is trying to quit smoking? A. A pumpkin patch!!!', 
'Q. Where do vampires keep their money? A: The blood bank!!!', 
'Q. Who are some of the were-wolves cousins? A. The what-wolves and when-wolves.', 
'Q. What did Dracula say after reading all these jokes? A. They suck! (or they bite!)', 
'Q. What do ghosts have in their noses? A. Boo- gers', 
'Q. What does the devil keep between his legs? A.Great balls of fire.', 
'Q. Why do men ghosts like girl ghosts? A. Because they have big boo-bies!', 
'Q. What did the lady ghost name her weener-dog? A. Holly-weeny', 
'Q. What do you get when you goose a ghost? A. A handful of sheet!', 
'Q. What did Dracula say after reading all these jokes? A. They suck!', 
'Q: Why cant two ghosts kiss? A: cause theyd go right through each other!', 
'Q: What are the two lumps on a girl ghosts upper half?A:boooooobies', 
'Q: Why do ghosts scare people?A: They hope theyll scare the LIVING soul out of them!', 
'Q: Why dont you ever see ghosts poop?A: Because its invisable!', 
'Q: Where is a ghosts favorite place to eat? A: BOOOOOOOger King.', 
'Q: What did the owl say to the girl ghost as shewalked by? A: Nice HOOOOOTERS!', 
'Q: What did the boy vampire say to the girl? A: Let me get a suck of that.', 
'Q: What did the ghost say when the boy told him a joke? A: You KILL me!', 
'Q: Why was the vampires face white? A: Because he got the living-daylight sucked out of him']
randjoke = random.choice(jokes) #Choose random Joke

dt = datetime.datetime.now()
month = datetime.date.today().strftime("%B") #Month e.g. Dec
#print month
daynumber = datetime.datetime.now().day 

mon = 10 - dt.month
Xday = 30 - dt.day
hr = 23 - dt.hour
mn = 60 - dt.minute
sec = 60 - dt.second

if month == "October" and daynumber < 31:
	time2wait = random.randint(1,37600) #random time in next 10 hours
	print time2wait
	time.sleep(time2wait)
	s = repr(Xday) + ' days ' + repr(hr) + ' hours ' + repr(mn) + ' mins ' + repr(sec) + ' secs' + ' until Halloween'
	#print s
	push = pb.push_note(s, randjoke)
elif month == "October" and daynumber == 31:
	s = "THIS IS HALLOWEEN!"
	b = "Time to Scare some people"
	push = pb.push_note(s, b)
else:
	print ""
